# https://raw.githubusercontent.com/sxyazi/yazi/HEAD/yazi-config/preset/yazi.toml

[manager]
ratio = [1, 2, 3]
sort_by = "natural"
linemode = "size"
show_hidden = true

[preview]
wrap = "yes"
tab_size = 4
max_width = 1600
max_height = 1900

[open]
prepend_rules = [
  { name = "*/", use = ["open", "reveal"] },
  { mime = "{audio,video}/*", use = ["open", "reveal"] },
]
